
const KEY='diesel_stand_v1';
let db;
const empty=()=>({configured:false,settings:{name:'بسطة مازوت',owner:'عبدالله ناعس',salePrice:0,minStock:100,theme:'green',pinEnabled:'no',pin:''},cash:0,stock:0,avgCost:0,people:[],sales:[],purchases:[],expenses:[],cashMoves:[],stockMoves:[],payments:[]});
function load(){try{db=JSON.parse(localStorage.getItem(KEY))||empty()}catch(e){db=empty()}if(!db.payments)db.payments=[];if(!db.stockMoves)db.stockMoves=[];applyTheme();}
function save(){localStorage.setItem(KEY,JSON.stringify(db));render();}
const $=id=>document.getElementById(id);const n=v=>Number(v||0);const money=v=>(Number(v||0)).toFixed(2)+' $';const lit=v=>(Number(v||0)).toFixed(2)+' لتر';const today=()=>new Date().toISOString().slice(0,10);const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
function dateIn(d,from,to){return (!from||d>=from)&&(!to||d<=to)}function personName(id){return (db.people.find(p=>p.id===id)||{}).name||'نقدي / غير محدد'}
function applyTheme(){document.body.className=db.settings.theme||'green'}
function initDates(){['saleDate','purDate','stockDate','cashDate','expDate','payDate','repFrom','repTo'].forEach(id=>{if($(id)&&!$(id).value)$(id).value=today()});}
function start(){load();initDates();if(!db.configured){$('setupPage').classList.remove('hidden');document.querySelector('nav').classList.add('hidden');document.querySelector('.header').classList.add('hidden');return}else{$('setupPage').classList.add('hidden');document.querySelector('nav').classList.remove('hidden');document.querySelector('.header').classList.remove('hidden')}if(db.settings.pinEnabled==='yes'&&db.settings.pin){$('lock').classList.remove('hidden')}render();}
function unlock(){if($('pinInput').value===db.settings.pin){$('lock').classList.add('hidden');$('pinMsg').textContent=''}else $('pinMsg').textContent='الرمز غير صحيح'}
function finishSetup(){db=empty();db.configured=true;db.settings.name=$('setName').value||'بسطة مازوت';db.settings.owner=$('setOwner').value||'';db.settings.salePrice=n($('setSalePrice').value);db.settings.pinEnabled=$('setPinEnabled').value;db.settings.pin=$('setPin').value;db.cash=n($('setCash').value);db.stock=n($('setStock').value);db.avgCost=n($('setCost').value);db.cashMoves.push({id:uid(),date:today(),type:'in',amount:db.cash,note:'كاش افتتاحي'});db.stockMoves.push({id:uid(),date:today(),type:'set',qty:db.stock,note:'مخزون افتتاحي'});save();location.reload();}
function go(page,btn){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));$(page).classList.add('active');document.querySelectorAll('.tabs button').forEach(b=>b.classList.remove('active'));if(btn)btn.classList.add('active');if(page==='reports')renderReports();if(page==='settings')fillSettings();window.scrollTo({top:0,behavior:'smooth'});}
function totals(from='',to=''){let sales=db.sales.filter(x=>dateIn(x.date,from,to)),purs=db.purchases.filter(x=>dateIn(x.date,from,to)),exps=db.expenses.filter(x=>dateIn(x.date,from,to));let sLit=sales.reduce((a,b)=>a+n(b.liters),0),sTotal=sales.reduce((a,b)=>a+n(b.total),0),sPaid=sales.reduce((a,b)=>a+n(b.paid),0),profit=sales.reduce((a,b)=>a+n(b.profit),0);let pLit=purs.reduce((a,b)=>a+n(b.liters),0),pTotal=purs.reduce((a,b)=>a+n(b.total),0),pPaid=purs.reduce((a,b)=>a+n(b.paid),0);let exp=exps.reduce((a,b)=>a+n(b.amount),0);return{sales,purs,exps,sLit,sTotal,sPaid,profit,pLit,pTotal,pPaid,exp};}
function receivable(personId){let a=db.sales.filter(s=>!personId||s.personId===personId).reduce((x,s)=>x+n(s.total)-n(s.paid),0);let b=db.payments.filter(p=>(!personId||p.personId===personId)&&p.type==='collect').reduce((x,p)=>x+n(p.amount),0);return a-b}
function payable(personId){let a=db.purchases.filter(s=>!personId||s.personId===personId).reduce((x,s)=>x+n(s.total)-n(s.paid),0);let b=db.payments.filter(p=>(!personId||p.personId===personId)&&p.type==='pay_supplier').reduce((x,p)=>x+n(p.amount),0);return a-b}
function render(){if(!db||!db.configured)return;applyTheme();$('appTitle').textContent=db.settings.name;$('appSub').textContent='إدارة مبيعات ومشتريات وكاش وديون';$('todayChip').textContent='اليوم: '+today();$('ownerChip').textContent='المالك: '+(db.settings.owner||'غير محدد');$('headCash').textContent=money(db.cash);$('headStock').textContent=lit(db.stock);$('headReceivable').textContent=money(receivable());$('headPayable').textContent=money(payable());$('headProfit').textContent=money(totals(today(),today()).profit);if($('salePrice')&&!$('salePrice').value)$('salePrice').value=db.settings.salePrice||'';renderSelects();renderDashboard();renderSales();renderPurchases();renderCash();renderPeople();}
function kpi(label,value,cls=''){return `<div class="kpi"><span>${label}</span><b class="${cls}">${value}</b></div>`}
function renderDashboard(){let td=tult=today(),t=tots=totals(today(),today()),all=totals();$('dashKpis').innerHTML=[kpi('مبيعات اليوم',money(t.sTotal)),kpi('لترات مباعة اليوم',lit(t.sLit)),kpi('ربح اليوم',money(t.profit),'goodtxt'),kpi('مصاريف اليوم',money(t.exp),'badtxt'),kpi('إجمالي المبيعات',money(all.sTotal)),kpi('إجمالي المشتريات',money(all.pTotal)),kpi('متوسط كلفة اللتر',money(db.avgCost)),kpi('قيمة المخزون التقريبية',money(db.stock*db.avgCost))].join('');let alerts=[];if(db.stock<=n(db.settings.minStock))alerts.push(['تنبيه مخزون','المخزون أقل من الحد المحدد: '+lit(db.stock),'badtxt']);if(receivable()>0)alerts.push(['ديون للبسطة','يوجد مبالغ على الزبائن: '+money(receivable()),'goodtxt']);if(payable()>0)alerts.push(['ديون على البسطة','يوجد مبالغ للموردين: '+money(payable()),'badtxt']);if(db.cash<0)alerts.push(['الكاش ناقص','راجع المبيعات والمصاريف والدفعات','badtxt']);if(!alerts.length)alerts.push(['الوضع جيد','لا توجد تنبيهات مهمة الآن','goodtxt']);$('alerts').innerHTML=alerts.map(a=>`<div class="item"><div><h3 class="${a[2]}">${a[0]}</h3><p>${a[1]}</p></div><span class="badge">تنبيه</span></div>`).join('');let events=[...db.sales.map(x=>({...x,kind:'بيع'})),...db.purchases.map(x=>({...x,kind:'شراء'})),...db.expenses.map(x=>({...x,kind:'مصروف'})),...db.payments.map(x=>({...x,kind:'دفعة'}))].sort((a,b)=>b.id.localeCompare(a.id)).slice(0,8);$('recentList').innerHTML=events.length?events.map(e=>`<div class="item"><div><h3>${e.kind} - ${e.date}</h3><p>${personName(e.personId)} | ${e.liters?lit(e.liters):''} ${e.amount?money(e.amount):money(e.total||0)} ${e.note||''}</p></div><span class="badge">${e.kind}</span></div>`).join(''):'<div class="notice">لا يوجد حركات بعد.</div>'}
function renderSelects(){let opts='<option value="">نقدي / غير محدد</option>'+db.people.map(p=>`<option value="${p.id}">${p.name} - ${p.type==='supplier'?'مورد':p.type==='customer'?'زبون':'زبون ومورد'}</option>`).join('');['salePerson','purPerson','payPerson'].forEach(id=>{if($(id)){let old=$(id).value;$(id).innerHTML=opts;$(id).value=old}})}
function addPerson(){let name=$('personName').value.trim();if(!name)return alert('اكتب اسم الشخص');db.people.push({id:uid(),name,type:$('personType').value,phone:$('personPhone').value,note:$('personNote').value});['personName','personPhone','personNote'].forEach(id=>$(id).value='');save();}
function addSale(){let liters=n($('saleLiters').value),price=n($('salePrice').value),paid=n($('salePaid').value),date=$('saleDate').value||today();if(liters<=0||price<=0)return alert('أدخل الكمية وسعر اللتر');if(liters>db.stock&&!confirm('الكمية أكبر من المخزون الحالي. هل تريد المتابعة؟'))return;let total=liters*price;if($('saleType').value==='cash')paid=total;if(paid>total)paid=total;let cost=db.avgCost,profit=(price-cost)*liters;db.sales.push({id:uid(),date,personId:$('salePerson').value,liters,price,total,paid,cost,profit,note:$('saleNote').value});db.stock-=liters;db.cash+=paid;['saleLiters','salePaid','saleNote'].forEach(id=>$(id).value='');save();}
function fillPaidTotal(){let total=n($('saleLiters').value)*n($('salePrice').value);$('salePaid').value=total.toFixed(2)}
function addPurchase(){let liters=n($('purLiters').value),price=n($('purPrice').value),paid=n($('purPaid').value),date=$('purDate').value||today();if(liters<=0||price<=0)return alert('أدخل الكمية وسعر الشراء');let total=liters*price;if(paid>total)paid=total;let oldValue=db.stock*db.avgCost;db.stock+=liters;db.avgCost=db.stock>0?(oldValue+total)/db.stock:0;db.cash-=paid;db.purchases.push({id:uid(),date,personId:$('purPerson').value,liters,price,total,paid,invoice:$('purInvoice').value,note:$('purNote').value});['purLiters','purPrice','purPaid','purInvoice','purNote'].forEach(id=>$(id).value='');save();}
function fillPurchasePaid(){let total=n($('purLiters').value)*n($('purPrice').value);$('purPaid').value=total.toFixed(2)}
function addStockMove(){let qty=n($('stockQty').value),type=$('stockType').value,date=$('stockDate').value||today();if(qty<=0)return alert('أدخل الكمية');if(type==='loss')db.stock-=qty;else if(type==='add')db.stock+=qty;else db.stock=qty;db.stockMoves.push({id:uid(),date,type,qty,note:$('stockNote').value});$('stockQty').value='';$('stockNote').value='';save();}
function addCashMove(){let amount=n($('cashAmount').value),type=$('cashType').value,date=$('cashDate').value||today();if(amount<=0)return alert('أدخل المبلغ');db.cash+=type==='in'?amount:-amount;db.cashMoves.push({id:uid(),date,type,amount,note:$('cashNote').value});$('cashAmount').value='';$('cashNote').value='';save();}
function addExpense(){let amount=n($('expAmount').value),date=$('expDate').value||today();if(amount<=0)return alert('أدخل مبلغ المصروف');db.cash-=amount;db.expenses.push({id:uid(),date,cat:$('expCat').value,amount,note:$('expNote').value});$('expAmount').value='';$('expNote').value='';save();}
function addPayment(){let amount=n($('payAmount').value),date=$('payDate').value||today(),type=$('payType').value,personId=$('payPerson').value;if(amount<=0||!personId)return alert('اختر الشخص وأدخل المبلغ');db.cash+=type==='collect'?amount:-amount;db.payments.push({id:uid(),date,type,personId,amount,note:$('payNote').value});$('payAmount').value='';$('payNote').value='';save();}
function del(arr,id){if(confirm('حذف هذه الحركة؟')){db[arr]=db[arr].filter(x=>x.id!==id);recalcAll();save();}}
function recalcAll(){let baseStock=0,baseCash=0,baseCost=0;let firstStock=db.stockMoves.find(x=>x.note==='مخزون افتتاحي');let firstCash=db.cashMoves.find(x=>x.note==='كاش افتتاحي');baseStock=firstStock?n(firstStock.qty):0;baseCash=firstCash?n(firstCash.amount):0;baseCost=db.avgCost;db.cash=baseCash;db.stock=baseStock;let initialCost=baseCost;db.avgCost=initialCost;let events=[...db.purchases.map(x=>({...x,k:'p'})),...db.sales.map(x=>({...x,k:'s'})),...db.expenses.map(x=>({...x,k:'e'})),...db.cashMoves.filter(x=>x.note!=='كاش افتتاحي').map(x=>({...x,k:'c'})),...db.stockMoves.filter(x=>x.note!=='مخزون افتتاحي').map(x=>({...x,k:'st'})),...db.payments.map(x=>({...x,k:'pay'}))].sort((a,b)=>a.date.localeCompare(b.date)||a.id.localeCompare(b.id));events.forEach(e=>{if(e.k==='p'){let old=db.stock*db.avgCost;db.stock+=n(e.liters);db.avgCost=db.stock>0?(old+n(e.total))/db.stock:0;db.cash-=n(e.paid)}if(e.k==='s'){db.stock-=n(e.liters);db.cash+=n(e.paid)}if(e.k==='e')db.cash-=n(e.amount);if(e.k==='c')db.cash+=e.type==='in'?n(e.amount):-n(e.amount);if(e.k==='st'){if(e.type==='loss')db.stock-=n(e.qty);else if(e.type==='add')db.stock+=n(e.qty);else db.stock=n(e.qty)}if(e.k==='pay')db.cash+=e.type==='collect'?n(e.amount):-n(e.amount)})}
function table(headers,rows){return `<div class="tableWrap"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')||`<tr><td colspan="${headers.length}">لا توجد بيانات</td></tr>`}</tbody></table></div>`}
function renderSales(){let q=($('salesSearch')?.value||'').trim(),from=$('salesFrom')?.value||'',to=$('salesTo')?.value||'';let rows=db.sales.filter(s=>dateIn(s.date,from,to)&&(personName(s.personId).includes(q)||(s.note||'').includes(q))).sort((a,b)=>b.date.localeCompare(a.date)).map(s=>`<tr><td>${s.date}</td><td>${personName(s.personId)}</td><td>${lit(s.liters)}</td><td>${money(s.price)}</td><td>${money(s.total)}</td><td>${money(s.paid)}</td><td>${money(n(s.total)-n(s.paid))}</td><td class="${s.profit>=0?'goodtxt':'badtxt'}">${money(s.profit)}</td><td>${s.note||''}</td><td><button class="btn small danger" onclick="del('sales','${s.id}')">حذف</button></td></tr>`);$('salesTable').innerHTML=table(['التاريخ','الزبون','الكمية','السعر','الإجمالي','المدفوع','الباقي','الربح','ملاحظة',''],rows)}
function renderPurchases(){let rows=db.purchases.sort((a,b)=>b.date.localeCompare(a.date)).map(p=>`<tr><td>${p.date}</td><td>${personName(p.personId)}</td><td>${lit(p.liters)}</td><td>${money(p.price)}</td><td>${money(p.total)}</td><td>${money(p.paid)}</td><td>${money(n(p.total)-n(p.paid))}</td><td>${p.invoice||''}</td><td>${p.note||''}</td><td><button class="btn small danger" onclick="del('purchases','${p.id}')">حذف</button></td></tr>`);let st=db.stockMoves.filter(x=>x.note!=='مخزون افتتاحي').sort((a,b)=>b.date.localeCompare(a.date)).map(s=>`<tr><td>${s.date}</td><td colspan="2">تسوية مخزون</td><td>${s.type==='loss'?'نقص':s.type==='add'?'زيادة':'تثبيت'}</td><td>${lit(s.qty)}</td><td colspan="4">${s.note||''}</td><td><button class="btn small danger" onclick="del('stockMoves','${s.id}')">حذف</button></td></tr>`);$('purchaseTable').innerHTML=table(['التاريخ','المورد/النوع','الكمية','سعر/نوع','الإجمالي/كمية','المدفوع','الباقي','فاتورة','ملاحظة',''],rows.concat(st))}
function renderCash(){let rows=[...db.cashMoves.map(x=>({...x,k:'كاش'})),...db.expenses.map(x=>({...x,k:'مصروف'})),...db.payments.map(x=>({...x,k:'دفعة'}))].sort((a,b)=>b.date.localeCompare(a.date)).map(x=>{let amount=x.k==='مصروف'?-n(x.amount):x.k==='دفعة'?(x.type==='collect'?n(x.amount):-n(x.amount)):(x.type==='in'?n(x.amount):-n(x.amount));let arr=x.k==='مصروف'?'expenses':x.k==='دفعة'?'payments':'cashMoves';return `<tr><td>${x.date}</td><td>${x.k}</td><td>${x.cat||x.type||''}</td><td class="${amount>=0?'goodtxt':'badtxt'}">${money(amount)}</td><td>${personName(x.personId)}</td><td>${x.note||''}</td><td><button class="btn small danger" onclick="del('${arr}','${x.id}')">حذف</button></td></tr>`});$('cashTable').innerHTML=table(['التاريخ','الحركة','النوع','المبلغ','الشخص','ملاحظة',''],rows)}
function renderPeople(){let rows=db.people.map(p=>{let r=receivable(p.id),pa=payable(p.id);return `<div class="item"><div><h3>${p.name}</h3><p><span class="badge">${p.type==='supplier'?'مورد':p.type==='customer'?'زبون':'زبون ومورد'}</span> ${p.phone||''} ${p.note||''}<br>دين لنا: <b class="goodtxt">${money(r)}</b> | دين علينا: <b class="badtxt">${money(pa)}</b></p></div><button class="btn small danger" onclick="delPerson('${p.id}')">حذف</button></div>`});$('peopleList').innerHTML=rows.join('')||'<div class="notice">لا يوجد أشخاص بعد.</div>'}
function delPerson(id){if(db.sales.some(x=>x.personId===id)||db.purchases.some(x=>x.personId===id)||db.payments.some(x=>x.personId===id))return alert('لا يمكن حذف شخص لديه حركات. احذف الحركات أولًا.');db.people=db.people.filter(p=>p.id!==id);save();}
function clearFilters(kind){if(kind==='sales'){['salesSearch','salesFrom','salesTo'].forEach(id=>$(id).value='')}render()}
function renderReports(){let from=$('repFrom').value,to=$('repTo').value,t=totals(from,to);$('reportTitle').textContent=`تقرير ${db.settings.name} من ${from||'البداية'} إلى ${to||'اليوم'}`;$('reportKpis').innerHTML=[kpi('إجمالي المبيعات',money(t.sTotal)),kpi('لترات مباعة',lit(t.sLit)),kpi('إجمالي المشتريات',money(t.pTotal)),kpi('لترات مشتراة',lit(t.pLit)),kpi('الربح قبل المصاريف',money(t.profit),'goodtxt'),kpi('المصاريف',money(t.exp),'badtxt'),kpi('الصافي التقريبي',money(t.profit-t.exp),t.profit-t.exp>=0?'goodtxt':'badtxt'),kpi('الكاش الحالي',money(db.cash))].join('');let details='';if($('repType').value!=='debts'){details+=`<h3>المبيعات</h3>`+table(['التاريخ','الزبون','لتر','الإجمالي','المدفوع','الربح'],t.sales.map(s=>`<tr><td>${s.date}</td><td>${personName(s.personId)}</td><td>${lit(s.liters)}</td><td>${money(s.total)}</td><td>${money(s.paid)}</td><td>${money(s.profit)}</td></tr>`));}if($('repType').value!=='sales'){details+=`<h3>الديون</h3>`+table(['الشخص','دين لنا','دين علينا'],db.people.map(p=>`<tr><td>${p.name}</td><td>${money(receivable(p.id))}</td><td>${money(payable(p.id))}</td></tr>`));}$('reportDetails').innerHTML=details||'<div class="notice">لا توجد بيانات.</div>'}
function printReport(){go('reports',document.querySelector('[data-page="reports"]'));renderReports();setTimeout(()=>window.print(),200)}
function fillSettings(){$('optName').value=db.settings.name;$('optOwner').value=db.settings.owner;$('optSalePrice').value=db.settings.salePrice;$('optMinStock').value=db.settings.minStock;$('optTheme').value=db.settings.theme;$('optPinEnabled').value=db.settings.pinEnabled;$('optPin').value=''}
function saveSettings(){db.settings.name=$('optName').value||'بسطة مازوت';db.settings.owner=$('optOwner').value;db.settings.salePrice=n($('optSalePrice').value);db.settings.minStock=n($('optMinStock').value);db.settings.theme=$('optTheme').value;db.settings.pinEnabled=$('optPinEnabled').value;if($('optPin').value)db.settings.pin=$('optPin').value;save();alert('تم حفظ الإعدادات')}
function exportData(){let blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'});download(blob,'backup-diesel-stand-'+today()+'.json')}
function exportCSV(){let lines=['type,date,person,liters,total,paid,note'];db.sales.forEach(s=>lines.push(['sale',s.date,personName(s.personId),s.liters,s.total,s.paid,s.note||''].join(',')));db.purchases.forEach(p=>lines.push(['purchase',p.date,personName(p.personId),p.liters,p.total,p.paid,p.note||''].join(',')));let blob=new Blob([lines.join('\n')],{type:'text/csv'});download(blob,'diesel-stand-'+today()+'.csv')}
function download(blob,name){let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href)}
function importData(ev){let f=ev.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let x=JSON.parse(r.result);if(!x.settings)throw 0;db=x;save();alert('تم استيراد النسخة');location.reload()}catch(e){alert('ملف غير صالح')}};r.readAsText(f)}
function resetAll(){if(confirm('هل أنت متأكد من حذف كل البيانات؟')){localStorage.removeItem(KEY);location.reload();}}
start();
